// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
// แก้ไขไฟล์ prisma.config.ts
import { defineConfig } from '@prisma/config'

export default defineConfig({
  schema: './prisma/schema.prisma',
  datasource: {
    // 🌟 ให้ใช้ DIRECT_URL (พอร์ต 5432 ของ Supabase) ในการ Migrate โครงสร้าง
    url: process.env.DIRECT_URL, 
  },
})
